[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "code-server --bind-addr 0.0.0.0:8080 --auth password"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PASSWORD = "your_secure_password_here"