name: code-server
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: vscode
  name: code-server
  instance_size_slug: basic-xxl  # 4GB RAM, 2 vCPUs
  instance_count: 1
  http_port: 10000
  routes:
  - path: /
  envs:
  - key: PASSWORD
    value: your_secure_password_here
    scope: RUN_TIME
    type: SECRET